import Head from "next/head";
import Header from "../components/Header";
import CardContainer from "../components/cardContainer";
import PenGlobeContainer from "../components/penGlobeContainer";
import Grid from "@mui/material/Unstable_Grid2";

export default function Home() {
  return (
    <>
      <Head>
        <title>Den App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ backgroundColor: "#d9d9d9" }}>
        <Grid container>
          <Grid item xs={12}>
            <Header />
          </Grid>
          <Grid item sx={{ width: "81.77%", margin: "2.5% 2% 2.5% 9.11%"}}>
            <CardContainer />
          </Grid>
          <Grid item>
            <PenGlobeContainer />
          </Grid>
        </Grid>
      </main>
    </>
  );
}
